name: Check code style
on:
  pull_request:
    paths:
      - .github/workflows/style.yml
      - '**/*.rs'
  workflow_dispatch:
jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          components: rustfmt
          override: true

      - name: Check formatting
        run: |
          rustfmt --version
          cargo fmt -- --check

  check-linting:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          components: clippy
          override: true

      - name: Run linter
        shell: bash
        run: RUSTFLAGS="--deny warnings" cargo clippy --verbose
